import KeyboardRow from "./KeyboardRow";

export default function Keyboard({
  keyboard,
  setGuessInput,
  setGuesses,
  guessCount,
  inputRef,
  handleGuess,
}) {
  return (
    <>
      <KeyboardRow
        values={[
          keyboard[16].value,
          keyboard[22].value,
          keyboard[4].value,
          keyboard[17].value,
          keyboard[19].value,
          keyboard[24].value,
          keyboard[20].value,
          keyboard[8].value,
          keyboard[14].value,
          keyboard[15].value,
        ]}
        colors={[
          keyboard[16].color,
          keyboard[22].color,
          keyboard[4].color,
          keyboard[17].color,
          keyboard[19].color,
          keyboard[24].color,
          keyboard[20].color,
          keyboard[8].color,
          keyboard[14].color,
          keyboard[15].color,
        ]}
        setGuessInput={setGuessInput}
        setGuesses={setGuesses}
        guessCount={guessCount}
        inputRef={inputRef}
        handleGuess={handleGuess}
      />
      <KeyboardRow
        values={[
          keyboard[0].value,
          keyboard[18].value,
          keyboard[3].value,
          keyboard[5].value,
          keyboard[6].value,
          keyboard[7].value,
          keyboard[9].value,
          keyboard[10].value,
          keyboard[11].value,
        ]}
        colors={[
          keyboard[0].color,
          keyboard[18].color,
          keyboard[3].color,
          keyboard[5].color,
          keyboard[6].color,
          keyboard[7].color,
          keyboard[9].color,
          keyboard[10].color,
          keyboard[11].color,
        ]}
        setGuessInput={setGuessInput}
        setGuesses={setGuesses}
        guessCount={guessCount}
        inputRef={inputRef}
        handleGuess={handleGuess}
      />
      <KeyboardRow
        values={[
          "ENT",
          keyboard[25].value,
          keyboard[23].value,
          keyboard[2].value,
          keyboard[21].value,
          keyboard[1].value,
          keyboard[13].value,
          keyboard[12].value,
          "DEL",
        ]}
        colors={[
          "grey",
          keyboard[25].color,
          keyboard[23].color,
          keyboard[2].color,
          keyboard[21].color,
          keyboard[1].color,
          keyboard[13].color,
          keyboard[12].color,
          "grey",
        ]}
        setGuessInput={setGuessInput}
        setGuesses={setGuesses}
        guessCount={guessCount}
        inputRef={inputRef}
        handleGuess={handleGuess}
      ></KeyboardRow>
    </>
  );
}
